# Generated by Django 2.2.6 on 2019-10-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PictureModel',
            new_name='Picture',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='logo',
            new_name='image',
        ),
    ]
